### ISSUE TITLE
segmentation violation in FindStringSubmatchIndex

### ISSUE THREAD

**Issue by itaischwartz** [wasilibs/go-re2#98]
I suspect that in `FindStringSubmatchIndex`, the code calls `newCString` on `s`, but there is no guarantee that the GC won't free it later, which can result in memory corruption.

How to reproduce:
```
package main_test

import (
	"fmt"
	"math/rand"
	"runtime"
	"testing"
	"time"

        regexp "github.com/wasilibs/go-re2"
)

func TestCStringRe2(t *testing.T) {
	t.Parallel()

	t.Logf("lib: %s", regexp.Implementation.Value)
	pat := regexp.MustCompile(`(?m)(?:^|\b)(?P<pattern>[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,4})(?:$|\b)`)

	go func() {
		ticker := time.NewTicker(time.Millisecond * 100)
		for {
			<-ticker.C
			// time.Sleep(time.Millisecond * 100)
			runtime.GC()
		}
	}()
	for i := range 10 {
		t.Run(fmt.Sprintf("test-%d", i), func(t *testing.T) {
			t.Parallel()

			body := string(randSeq(1024*1024*100, 0, letters))
			_ = pat.FindStringSubmatchIndex(body)

			// fmt.Println(ms)
		})
	}
}

// nolint: gosec
func randSeq(n int, seed int64, letters []rune) []byte {
	b := make([]rune, n)
	src := rand.New(rand.NewSource(seed))
	for i := range b {
		b[i] = letters[src.Intn(len(letters))]
	}
	return []byte(string(b))
}

var letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
```
`GOMAXPROCS=1 go test -tags re2_cgo ./cmd/re2_test.go -count=1 -v`
result:
```
SIGSEGV: segmentation violation
PC=0x10544cc44 m=5 sigcode=2 addr=0x10f
signal arrived during cgo execution

goroutine 9 gp=0x140000ae000 m=5 mp=0x14000050408 [syscall]:
runtime.cgocall(0x104db7020, 0x1400005ad18)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x1400005ace0 sp=0x1400005aca0 pc=0x104cbc2e4
github.com/wasilibs/go-re2/internal/cre2._Cfunc_cre2_match(0x14160b010, 0x14025902000, 0x6400000, 0x0, 0x6400000, 0x0, 0x131804080, 0x2)
        _cgo_gotypes.go:216 +0x34 fp=0x1400005ad10 sp=0x1400005ace0 pc=0x104db4564
github.com/wasilibs/go-re2/internal.match.Match.func1(0x14160b010, 0x14025902000, 0x6400000, 0x0, 0x6400000, 0x0, 0x131804080, 0x2)
        /Users/test/projects/re2_test/go-re2/internal/cre2/cre2.go:61 +0xc8 fp=0x1400005ad60 sp=0x1400005ad10 pc=0x104db6428
github.com/wasilibs/go-re2/internal/cre2.Match(...)
        /Users/test/projects/re2_test/go-re2/internal/cre2/cre2.go:61
github.com/wasilibs/go-re2/internal.match(0x8?, {0x14025902000?, 0x140000860d0?}, 0x0?, 0x5ae28?)
        /Users/test/projects/re2_test/go-re2/internal/re2_tinygowasm.go:75 +0x38 fp=0x1400005adb0 sp=0x1400005ad60 pc=0x104db6318
github.com/wasilibs/go-re2/internal.(*Regexp).findSubmatch(0x140000761e0, 0x1400005ae67, {0x14025902000?, 0x1?}, 0x1400005aef0)
        /Users/test/projects/re2_test/go-re2/internal/re2.go:613 +0x8c fp=0x1400005ae30 sp=0x1400005adb0 pc=0x104db583c
github.com/wasilibs/go-re2/internal.(*Regexp).FindStringSubmatchIndex(0x140000761e0, {0x14025902000?, 0x6400000?})
        /Users/test/projects/re2_test/go-re2/internal/re2.go:601 +0x10c fp=0x1400005af10 sp=0x1400005ae30 pc=0x104db560c
command-line-arguments_test.TestCStringRe2.func2(0x140000889c0?)
        /Users/test/projects/re2_test/cmd/re2_test.go:32 +0x84 fp=0x1400005af60 sp=0x1400005af10 pc=0x104db6ac4
testing.tRunner(0x140000889c0, 0x1400000e120)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1689 +0xec fp=0x1400005afb0 sp=0x1400005af60 pc=0x104d7d5bc
testing.(*T).Run.gowrap1()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1742 +0x2c fp=0x1400005afd0 sp=0x1400005afb0 pc=0x104d7e40c
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400005afd0 sp=0x1400005afd0 pc=0x104d29554
created by testing.(*T).Run in goroutine 6
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1742 +0x318

goroutine 1 gp=0x140000021c0 m=nil [chan receive]:
runtime.gopark(0x8?, 0x6?, 0x38?, 0xf9?, 0x104cbe288?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400005f8f0 sp=0x1400005f8d0 pc=0x104cf2fa8
runtime.chanrecv(0x14000028150, 0x0, 0x1)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:583 +0x404 fp=0x1400005f970 sp=0x1400005f8f0 pc=0x104cbe7a4
runtime.chanrecv1(0x140000222a0?, 0x104dfe720?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:442 +0x14 fp=0x1400005f9a0 sp=0x1400005f970 pc=0x104cbe394
testing.tRunner.func1()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1650 +0x43c fp=0x1400005fb40 sp=0x1400005f9a0 pc=0x104d7dabc
testing.tRunner(0x140000884e0, 0x1400005fc58)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1695 +0x128 fp=0x1400005fb90 sp=0x1400005fb40 pc=0x104d7d5f8
testing.runTests(0x1400000e030, {0x104ee0d40, 0x1, 0x1}, {0x1400005fd18?, 0x104d6c170?, 0x104efd0c0?})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:2159 +0x3b0 fp=0x1400005fc80 sp=0x1400005fb90 pc=0x104d7ffb0
testing.(*M).Run(0x140000800a0)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:2027 +0x5a4 fp=0x1400005feb0 sp=0x1400005fc80 pc=0x104d7ece4
main.main()
        _testmain.go:47 +0x16c fp=0x1400005ff40 sp=0x1400005feb0 pc=0x104db6ebc
runtime.main()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:271 +0x28c fp=0x1400005ffd0 sp=0x1400005ff40 pc=0x104cf2b4c
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400005ffd0 sp=0x1400005ffd0 pc=0x104d29554

goroutine 2 gp=0x14000002c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400004af90 sp=0x1400004af70 pc=0x104cf2fa8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:408
runtime.forcegchelper()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:326 +0xb8 fp=0x1400004afd0 sp=0x1400004af90 pc=0x104cf2e08
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004afd0 sp=0x1400004afd0 pc=0x104d29554
created by runtime.init.6 in goroutine 1
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:314 +0x24

goroutine 3 gp=0x14000003180 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400004b760 sp=0x1400004b740 pc=0x104cf2fa8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:408
runtime.bgsweep(0x14000028070)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgcsweep.go:318 +0x108 fp=0x1400004b7b0 sp=0x1400004b760 pc=0x104cdd968
runtime.gcenable.gowrap1()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgc.go:203 +0x28 fp=0x1400004b7d0 sp=0x1400004b7b0 pc=0x104cd1b08
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004b7d0 sp=0x1400004b7d0 pc=0x104d29554
created by runtime.gcenable in goroutine 1
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgc.go:203 +0x6c

goroutine 4 gp=0x14000003340 m=nil [GC scavenge wait]:
runtime.gopark(0x5ea91d1?, 0x6553f100?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400004bf60 sp=0x1400004bf40 pc=0x104cf2fa8
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x104efd1e0)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x1400004bf90 sp=0x1400004bf60 pc=0x104cdb2ec
runtime.bgscavenge(0x14000028070)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgcscavenge.go:658 +0xac fp=0x1400004bfb0 sp=0x1400004bf90 pc=0x104cdb8ac
runtime.gcenable.gowrap2()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgc.go:204 +0x28 fp=0x1400004bfd0 sp=0x1400004bfb0 pc=0x104cd1aa8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004bfd0 sp=0x1400004bfd0 pc=0x104d29554
created by runtime.gcenable in goroutine 1
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mgc.go:204 +0xac

goroutine 5 gp=0x14000003880 m=nil [finalizer wait]:
runtime.gopark(0x0?, 0x104e29240?, 0x40?, 0x1?, 0x1000000010?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400004a580 sp=0x1400004a560 pc=0x104cf2fa8
runtime.runfinq()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mfinal.go:194 +0x108 fp=0x1400004a7d0 sp=0x1400004a580 pc=0x104cd0bd8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004a7d0 sp=0x1400004a7d0 pc=0x104d29554
created by runtime.createfing in goroutine 1
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/mfinal.go:164 +0x80

goroutine 6 gp=0x14000003a40 m=nil [chan receive]:
runtime.gopark(0x14000076180?, 0x104cbe4b8?, 0x58?, 0xd?, 0x104cbe288?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x14000060d10 sp=0x14000060cf0 pc=0x104cf2fa8
runtime.chanrecv(0x14000028230, 0x0, 0x1)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:583 +0x404 fp=0x14000060d90 sp=0x14000060d10 pc=0x104cbe7a4
runtime.chanrecv1(0x14000022300?, 0x104dfe720?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:442 +0x14 fp=0x14000060dc0 sp=0x14000060d90 pc=0x104cbe394
testing.tRunner.func1()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1650 +0x43c fp=0x14000060f60 sp=0x14000060dc0 pc=0x104d7dabc
testing.tRunner(0x14000088680, 0x104e28be0)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1695 +0x128 fp=0x14000060fb0 sp=0x14000060f60 pc=0x104d7d5f8
testing.(*T).Run.gowrap1()
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1742 +0x2c fp=0x14000060fd0 sp=0x14000060fb0 pc=0x104d7e40c
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x14000060fd0 sp=0x14000060fd0 pc=0x104d29554
created by testing.(*T).Run in goroutine 1
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1742 +0x318

goroutine 7 gp=0x14000003c00 m=nil [chan receive]:
runtime.gopark(0x1400004c758?, 0x104cd1c7c?, 0x0?, 0x9c?, 0x14000003c00?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/proc.go:402 +0xc8 fp=0x1400004c6f0 sp=0x1400004c6d0 pc=0x104cf2fa8
runtime.chanrecv(0x14000076600, 0x0, 0x1)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:583 +0x404 fp=0x1400004c770 sp=0x1400004c6f0 pc=0x104cbe7a4
runtime.chanrecv1(0x5f5e100?, 0x104d29554?)
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/chan.go:442 +0x14 fp=0x1400004c7a0 sp=0x1400004c770 pc=0x104cbe394
command-line-arguments_test.TestCStringRe2.func1()
        /Users/test/projects/re2_test/cmd/re2_test.go:22 +0x38 fp=0x1400004c7d0 sp=0x1400004c7a0 pc=0x104db6cd8
runtime.goexit({})
        /opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/asm_arm64.s:1222 +0x4 fp=0x1400004c7d0 sp=0x1400004c7d0 pc=0x104d29554
created by command-line-arguments_test.TestCStringRe2 in goroutine 6
        /Users/test/projects/re2_test/cmd/re2_test.go:19 +0x90
```

**Comment by anuraaga** [comment]
Hi @itaischwartz - thanks for the report and repro! I wonder if you saw a crash in a real application and designed this unit test to try to reproduce it. I agree with code inspection that the `Index` methods didn't keep the input alive and fixed with #99. Unfortunately, I guess this unit test wasn't a repro for that specific issue, we can confirm it by adding `runtime.KeepAlive(body)` after the match in this test.

It looks like in situations of extremely aggressive GC, the `*Regexp` itself can get deallocated (and finalizer executed) during the execution of its method. Naturally this only affects the last iteration of the test, as well as `t.Parallel()` I think might be causing the pointer to be tracked more precisely as it ends up in a closure. I guess this problem doesn't affect any real-world app but it's still good to not crash like that so #100 should fix it.

**Comment by anuraaga** [comment]
@itaischwartz If my guess on this being a crash in a real app independent of this test repro is correct, would you be able to try the latest commit to see if it resolves it? Thanks!

**Comment by itaischwartz** [comment]
We are indeed investing a real app crash.
I'll try to see if this fix will change anything

**Comment by itaischwartz** [comment]
@anuraaga I updated to the latest commit, and I can still reproduce the issue

**Comment by anuraaga** [comment]
Thanks for the stacktrace @itaischwartz. Do you think you could try for another repro? The above test seems to be fixed now so I guess it's a different issue. I'll also see if tracing the stack trace brings up anything

**Comment by itaischwartz** [comment]
@anuraaga 
We're trying to create another repro.
It's not easy with memory issues...
I'm trying to debug with -msan

**Comment by itaischwartz** [comment]
@anuraaga Isn't the same problem applies to `ReplaceAllString` `src` paramter?
What about `rep1` in `replaceAll`?

**Comment by itaischwartz** [comment]
What about `FindStringSubmatch` 
Are we sure that the allocator will keep a ref to the string? He might optimize `matchedString` differently 
Isn't it just better to always explicitly call `defer runtime.KeepAlive` on refs?

**Comment by anuraaga** [comment]
`matchedString`, reads from the input string so there is no chance of a problem, the string has to be alive or there would be no way to read from it within the standard Go code. We don't want to add keepalive where not needed or it makes the code harder to reason about. That's why I removed a couple in #99.
